# msa-notice Secret
apiVersion: v1
kind: Secret
metadata:
  name: notice-secret
type: Opaque
data:
  DATABASE_USERNAME: 
  DATABASE_PASSWORD: 
  RABBITMQ_USERNAME: 
  RABBITMQ_PASSWORD: 
  OPENAI_API_KEY: 
  DATABASE_URL: 